
server:
  port: 80
spring:
  application:
    name: client-zuul
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
zuul:
  routes:
    cloud-web:
      path: /web/**
      serviceId: service-web
    cloud-excel:
      path: /excel/**
      serviceId: service-excel
    cloud-file:
      path: /file/**
      serviceId: service-file
