server:
  port: 9000
#spring:
#  application:
#    name: service-file
#配置阿里云oss
#aliyun:
#  oss:
#    flag: false
#    endpoint: oss-cn-zhangjiakou.aliyuncs.com
#    accessKeyId:
#    accessKeySecret:
#    bucketName:
