spring:
  application:
    #服务名称
    name: register-center
#  security:
#    user:
#      name: root
#      password: root
server:
  #服务端口
  port: 8761
#eureka配置
eureka:
  instance:
    hostname: localhost
#表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance,默认为90秒
    lease-expiration-duration-in-seconds: 15
#表示eureka client发送心跳给server端的频率,默认30秒
    lease-renewal-interval-in-seconds: 5
#    使用ip注册
    prefer-ip-address: true
#    注册显示id
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
#      注册地址
# 使用密码模式--> defaultZone: http://root:root@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#     是否将自己注册到eureka
    register-with-eureka: true
#    是否去注册中心获取其他服务的地址
    fetch-registry: false
#    表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 5
  server:
#    是否开启自我保护模式，默认为true
    enable-self-preservation: false
#    eureka server清理无效节点的时间间隔,默认60秒
    eviction-interval-timer-in-ms: 3000
